import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createNativeShell, validateApiBase } from '../native/native-shell-contract.js';
const rejected = ['', 'http://example.com', 'https://localhost', 'https://127.0.0.1', 'https://[::1]', 'https://u:p@example.com', 'https://example.com/api', 'https://example.com/?key=secret', 'https://example.com/#a'];
for (const base of rejected) assert.throws(() => validateApiBase(base), undefined, base);
assert.equal(validateApiBase('https://api.example.com/'), 'https://api.example.com');
let value = null; const calls = [];
const secure = { async get() { calls.push('get'); return { token: value }; }, async set({ token }) { calls.push('set'); value = token; }, async remove() { calls.push('remove'); value = null; } };
const web = createNativeShell({ isNative: false, apiBase: '', secure });
assert.equal(web.apiBase, ''); assert.equal(await web.secureSession.get(), null);
await web.secureSession.remove(); await assert.rejects(web.secureSession.set('token'), { code: 'NATIVE_UNAVAILABLE' });
await assert.rejects(web.capturePhoto(), { code: 'NATIVE_UNAVAILABLE' });
assert.deepEqual(calls, []);
const native = createNativeShell({ isNative: true, apiBase: 'https://api.example.com', secure, capturePhoto: async () => ({ dataUrl: 'data:image/jpeg;base64,abc', name: 'q.jpg' }), dictate: async () => ({ text: 'test' }), shareFile: async () => ({ name: 'backup.json' }) });
const token = 'opaque-test-session-0123456789';
await native.secureSession.set(token); assert.equal(await native.secureSession.get(), token);
await assert.rejects(native.secureSession.set('bad token')); assert.equal(value, token);
await native.secureSession.remove(); assert.equal(await native.secureSession.get(), null);
assert.deepEqual(await native.dictate(), { text: 'test' });
let fallback = 0; const back = [];
const off = native.onBack(() => { back.push('older'); return true; });
const offNew = native.onBack(() => { back.push('newer'); return false; });
assert.equal(await native.handleBack({ canGoBack: true }, () => fallback++), true);
assert.deepEqual(back, ['newer','older']); assert.equal(fallback, 0);
off(); offNew(); assert.equal(await native.handleBack({ canGoBack: false }, () => fallback++), false); assert.equal(fallback, 1);
const compat=fs.readFileSync(new URL('../public/native-compat.js',import.meta.url),'utf8');
const config=JSON.parse(fs.readFileSync(new URL('../capacitor.config.json',import.meta.url),'utf8'));
assert.equal(config.android.minWebViewVersion,116);
assert.equal(config.server.errorPath,'native-unavailable.html');
for(const missing of ['', 'timeout','any','randomUUID','structuredClone']){
 let destination='';const signal=function(){};signal.timeout=()=>{};signal.any=()=>{};
 const win={AbortSignal:signal,crypto:{randomUUID:()=>''},structuredClone:x=>x,location:{replace:value=>destination=value}};
 if(['timeout','any'].includes(missing))delete win.AbortSignal[missing];
 else if(missing==='randomUUID')delete win.crypto.randomUUID;
 else if(missing==='structuredClone')delete win.structuredClone;
 vm.runInNewContext(compat,{window:win});
 assert.equal(destination,missing?'/native-unavailable.html?reason=webview':'');
}
assert.ok(fs.readFileSync(new URL('../public/native-unavailable.html',import.meta.url),'utf8').includes('com.google.android.webview'));
console.log('Native boundary contracts passed: strict API origin, inert web path, secure token adapter, cancellable back handling. Android Keystore/device tests remain separate.');
