import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
await import('../public/catalog.js');
await import('../public/turkish-catalog.js');
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('root.RotaVideo='));
assert.ok(script);
const context={RotaCatalog,RotaTurkish,RotaCore:{validateBackup:x=>x},URL};context.window=context;vm.createContext(context);vm.runInContext(script,context);
const V=context.RotaVideo,plain=x=>JSON.parse(JSON.stringify(x)),tid='k-tr-1',vid='abcdefghijk';
const old={activeId:vid,customVideos:[{id:'zyxwvutsrqp',title:'Benim videom',teacher:'Kişisel kaynak',start:5}],positions:{[vid]:73},seriesActive:{'removed-old-series':vid},watched:[vid],updated:123};
const clean=V.validateLessons({[tid]:old},{customTopics:[]},'kpss');
assert.deepEqual(plain(clean[tid]),old,'Existing activity and optional links survive import unchanged');
const workspace={lessons:clean,topicState:{},customTopics:[],turkishPrefs:{'k-tr':'removed-old-series'}};
assert.deepEqual(plain(V.resources(workspace,tid)).map(x=>x.id),['zyxwvutsrqp',vid]);
assert.equal(V.resources(workspace,tid).find(x=>x.id===vid).start,73);
assert.equal(V.resources({lessons:{},topicState:{},customTopics:[]},tid).length,0,'A fresh student has no curated videos');
assert.throws(()=>V.validateLessons({[tid]:{...old,seriesActive:{constructor:vid}}},{customTopics:[]},'kpss'));
assert.throws(()=>V.validateLessons({'t-tr-1':old},{customTopics:[]},'kpss'));
assert.equal(V.parseYouTube('https://youtube.com.evil.test/watch?v='+vid),null);
assert.equal(V.parseYouTube('javascript:alert(1)'),null);
for(const forbidden of ['function campaignPage(','function chooseTurkishSeries(','V.SOURCES','TC.SERIES.some'])assert.ok(!html.includes(forbidden),forbidden);
for(const m of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g))if(!/application\/(?:json|ld\+json)/.test(m[1])&&m[2].trim())new Function(m[2]);
console.log('Personal sources passed: old links/notes/progress retained, cross-exam and unsafe keys rejected, catalog-free UI parses.');
