import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
await import('../public/catalog.js');
await import('../public/question-bank.js');
await import('../public/questions/kpss/blueprints.js');
for(let i=1;i<=4;i++)await import('../public/questions/kpss/tarih/ilk-turk-devletleri/test-'+i+'.js');
const B=globalThis.RotaQuestionBank,P=globalThis.RotaAssessmentBlueprints;
const tests=B.allTests(),all=tests.flatMap(t=>t.questions),report=B.audit();
assert.equal(tests.length,4);assert.equal(all.length,48);
assert.equal(report.approved,48,JSON.stringify(report.results.filter(r=>r.status!=='approved')));
assert.equal(report.duplicates.length,0);assert.deepEqual(report.testIssues,[]);
assert.equal(B.topicTests().length,4);
assert.ok(new Set(all.map(q=>q.subtopic)).size>=10,'Pilot must cover varied content, not word variants');
assert.ok(new Set(all.map(q=>q.questionType)).size>=6,'Pilot must measure multiple thinking processes');
assert.ok(all.filter(q=>q.questionType==='knowledge').length<24,'Recall must not dominate the pilot');
assert.ok(all.every(q=>Object.keys(q.wrongAnswerNotes).length===4));
const sample=structuredClone(all[0]);
const sign=q=>({...q,qualityStatus:'approved',review:{reviewer:'test-fixture',reviewedOn:'2026-09-23',fingerprint:B.fingerprint(q),checks:Object.fromEntries(B.REVIEW_CHECKS.map(k=>[k,true]))}});
assert.equal(B.validateQuestion(sample).status,'approved');
// Mathematical signs, powers, case and punctuation can distinguish the answers.
for(const options of [['−9','9','−3','3','0'],['2²','22','2³','23','2'],['Türkçe','türkçe','Türk’çe','Türk-çe','TürkÇe'],['Geldi.','Geldi?','Geldi!','Geldi,','Geldi;']]){
 const q={...sample,options};assert.ok(!B.validateQuestion(q).errors.includes('duplicate-options'));
}
assert.ok(B.validateQuestion({...sample,options:[' Aynı ','Aynı','B','C','D']}).errors.includes('duplicate-options'));
assert.equal(B.validateQuestion({...sample,text:sample.text+' İçerik değişti.'}).status,'needs-review','Editing an approved question revokes its review');
assert.equal(B.validateQuestion({...sample,qualityStatus:'needs-review'}).status,'needs-review');
assert.equal(B.validateQuestion({...sample,review:null}).status,'needs-review','A high quality score is not editorial evidence');
assert.equal(B.validateQuestion({...sample,options:['aynı','aynı','c','d','e']}).status,'rejected');
assert.equal(B.validateQuestion({...sample,answer:5}).status,'rejected');
assert.equal(B.validateQuestion(sign({...sample,lesson:'matematik'})).status,'rejected','Lesson metadata must agree with the existing subject ID');
assert.equal(B.validateQuestion(sign({...sample,topicId:'k-ma-1'})).status,'rejected','Topic metadata cannot point at a different subject');
assert.equal(B.validateQuestion({...sample,wrongAnswerNotes:{}}).status,'rejected');
assert.equal(B.validateQuestion({...sample,quality:{...sample.quality,distractorQuality:2}}).status,'needs-review');
const dated=sign({...sample,currentness:{required:true,verifiedOn:'2026-09-01',validUntil:'2026-09-22',sourceUrl:'https://www.mevzuat.gov.tr/'}});
assert.equal(B.validateQuestion(dated,{asOf:'2026-09-21'}).status,'needs-review','Future editorial review cannot approve a historical date');
assert.equal(B.validateQuestion(dated,{asOf:'2026-09-23'}).status,'needs-review','Stale legal facts stay quarantined');
const repeated=sign({...sample,id:'another-id',text:sample.text+' '});
assert.equal(B.audit([{...tests[0],questions:[sample,repeated]}]).duplicates.length,1,'Copying into a new ID must still be detected');
const overused=all.slice(0,4).map(q=>sign({...structuredClone(q),learningObjectiveId:'same-objective'}));
assert.ok(B.audit([{...tests[0],questions:overused}]).results.every(r=>r.warnings.includes('overused-objective')));
assert.ok(B.filter({lesson:'tarih',testNo:4,difficulty:'hard'}).length===6);
assert.ok(B.filter({questionType:'chronology'}).every(q=>q.questionType==='chronology'));
assert.ok(B.filter({learningObjectiveId:sample.learningObjectiveId}).some(q=>q.id===sample.id));
assert.equal(B.filter({qualityStatus:'needs-review'}).length,0);
const sandbox={};vm.runInNewContext(fs.readFileSync(new URL('../public/question-bank.js',import.meta.url),'utf8'),sandbox);
sandbox.RotaQuestionBank.registerTest({...tests[0],questions:[null,{},sample]});
assert.equal(sandbox.RotaQuestionBank.topicTests().length,0,'Malformed drafts cannot crash or publish');
assert.doesNotThrow(()=>sandbox.RotaQuestionBank.filter({search:'örnek'}));
const malformed={};vm.runInNewContext(fs.readFileSync(new URL('../public/question-bank.js',import.meta.url),'utf8'),malformed);
malformed.RotaQuestionBank.registerTest(tests[0]);
malformed.RotaQuestionBank.registerTest({...tests[1],questions:[{options:'bad'},{options:{}},null]});
assert.equal(malformed.RotaQuestionBank.topicTests().length,1,'Malformed draft option containers must be quarantined without breaking valid published tests');
const answers=tests[0].questions.map((q,i)=>i===0?-1:i===1?(q.answer+1)%5:q.answer);
const evidence=B.snapshot(tests[0],answers);
assert.equal(evidence.length,12);assert.equal(evidence[0].status,'blank');assert.equal(evidence[1].status,'wrong');
assert.equal(B.cleanEvidence([{...evidence[0],secret:'sensitive'}])[0].secret,undefined);
assert.equal(B.cleanEvidence([{...evidence[0],status:'correct'}]).length,0,'Outcome cannot disagree with the answer');
assert.equal(B.cleanEvidence([evidence[0],evidence[0]]).length,1);
const long='q'.repeat(120);assert.equal(B.cleanEvidence([{...evidence[0],questionId:long+'A'},{...evidence[0],questionId:long+'B'}]).length,1);
const attempts=[{id:'first',miniId:tests[0].id,date:'2026-09-23',created:1,questionEvidence:evidence},{id:'retake',miniId:tests[0].id,date:'2026-09-23',created:2,questionEvidence:B.snapshot(tests[0],tests[0].questions.map(q=>q.answer))}];
const signals=B.signals(attempts,{subjectId:'k-ta',topicId:'k-ta-1'});
assert.equal(signals.byType.reduce((n,x)=>n+x.total,0),12,'Same-day retakes count once');
assert.equal(signals.byType.reduce((n,x)=>n+x.wrong,0),0,'The latest same-day evidence wins');
assert.equal(B.signals(attempts,{subjectId:'k-ma'}).byType.length,0);
assert.equal(P.validate(RotaCatalog),true);assert.equal(P.sectionExams.length,18);assert.equal(P.compositeExams.length,3);
for(const bp of [...P.sectionExams,...P.compositeExams]){
 const result=B.assemble(bp,all);assert.equal(result.status,'needs-content');assert.equal(result.questions.length,0,'Incomplete exams must not masquerade as full papers');
}
const bp={id:'fixture',total:2,slots:[{subjectId:'k-ta',topicId:'k-ta-1',count:2}]};
const ready=B.assemble(bp,all);assert.equal(ready.status,'ready');assert.equal(ready.questions.length,2);
assert.deepEqual(B.assemble(bp,all).questions.map(q=>q.id),ready.questions.map(q=>q.id),'Assembly is reproducible');
assert.equal(B.assemble(bp,[sample,sample]).status,'needs-content','Duplicate pool entries cannot fill a quota');
const series=B.assembleSeries([bp,{...bp,id:'second'}],all);assert.equal(series.status,'ready');assert.equal(new Set(series.exams.flatMap(e=>e.questions.map(q=>q.id))).size,4,'Different variants cannot recycle the same questions');
const shortage=B.assembleSeries([bp,bp],ready.questions);assert.equal(shortage.status,'needs-content');assert.ok(shortage.exams.every(e=>e.questions.length===0));
console.log('Question bank passed: 48 approved original pilot items; quarantine, duplicate detection, evidence, 18 section blueprints and 3 future composite blueprints.');
