import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
const PORT=Number(process.env.RECOVERY_TEST_PORT||8853),BASE='http://127.0.0.1:'+PORT,KEY='calisma-rotasi:all:v5';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'rota-recovery-'));
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(PORT),HOST:'127.0.0.1',RENDER:'false',NODE_ENV:'test',ROTA_DB_PATH:path.join(tmp,'test.sqlite')},stdio:['ignore','pipe','pipe']});
let output='',browser;server.stdout.on('data',x=>output+=x);server.stderr.on('data',x=>output+=x);
const errors=[];
async function waitServer(){for(let i=0;i<100;i++){try{if((await fetch(BASE+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error(output);}
const nav=async(page,view)=>{await page.evaluate(v=>{document.querySelector('.sidebar [data-view="'+v+'"]').click();},view);};
const space=page=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)).workspaces.kpss,KEY);
const draft=page=>page.evaluate(k=>JSON.parse(localStorage.getItem(k+':preferences')).recoveryDrafts['k-ma-9'],KEY);
async function seed(page,{weak=true,empty=false}={}){
 await page.evaluate(({key,weak,empty})=>{
  const s=RotaCore.fresh(),w=s.workspaces.kpss;s.activeExam='kpss';w.configured=true;w.profile.completed=true;w.profile.summaryConfirmed=true;w.settings.name='Deniz';w.settings.days=[0,1,2,3,4,5,6];
  const pool=RotaQuestionBank.topicTests().flatMap(t=>t.questions).filter(q=>q.topicId==='k-ma-9').slice(0,20);
  w.assessments=empty?[]:(weak?[9,10,11]:[18,19,19]).map((correct,i)=>({id:'fixture-'+i,miniId:'fixture-'+i,subjectId:'k-ma',topicId:'k-ma-9',title:'Problemler',date:RotaCore.dayAdd(RotaCore.iso(),-3+i),total:20,correct,wrong:20-correct,blank:0,minutes:12,created:Date.now()-86400000*(3-i),questionEvidence:pool.map((q,j)=>({questionId:q.id,questionVersion:1,subjectId:q.subjectId,topicId:q.topicId,subtopic:q.subtopic,learningObjectiveId:q.learningObjectiveId,learningObjective:q.learningObjective,questionType:q.questionType,skill:q.skill,difficulty:q.difficulty,picked:j<correct?q.answer:(q.answer+1)%5,answer:q.answer,status:j<correct?'correct':'wrong'}))}));
  RotaCore.validateBackup(s);localStorage.setItem(key,JSON.stringify(s));localStorage.removeItem(key+':preferences');
 },{key:KEY,weak,empty});
 await page.reload({waitUntil:'networkidle'});await page.evaluate(()=>RotaAccount.ready);
}
async function answerAll(page,correct=true){
 const d=await draft(page),answers=await page.evaluate(({ids,correct})=>{const byId=new Map(RotaQuestionBank.topicTests().flatMap(t=>t.questions).map(q=>[q.id,q]));return ids.map(id=>{const a=byId.get(id).answer;return correct?a:(a+1)%5;});},{ids:d.questionIds,correct});
 for(let i=0;i<answers.length;i++)await page.locator('[name="recovery-q-'+i+'"][value="'+answers[i]+'"]').check();
 return d;
}
async function assertNoOverflow(page){const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,view:innerWidth}));assert.ok(size.scroll<=size.view+2,JSON.stringify(size));}
try{
 await waitServer();browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1365,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(BASE,{waitUntil:'networkidle'});await page.evaluate(()=>RotaAccount.ready);
 await seed(page);await nav(page,'recovery');assert.match(await page.locator('.content').innerText(),/3 ölçümde 60 soru/);assert.equal(await page.locator('[data-recovery-action="open"]').count(),1);
 await nav(page,'today');const task=(await space(page)).plan.find(p=>p.topicId==='k-ma-9'&&!p.done&&p.date===new Date().toISOString().slice(0,10));assert.ok(task,'Weak topic must have a today task');await page.locator('[data-action="focus-session"][data-id="'+task.id+'"]').first().click();assert.match(await page.locator('.content').innerText(),/Temel mantık/);await page.locator('[data-recovery-action="example"]').click();assert.match(await page.locator('.content').innerText(),/Nasıl düşünmeliyim/);await page.locator('[data-recovery-action="check"]').click();
 const d=await answerAll(page);assert.equal(d.questionIds.length,5);assert.ok(!d.questionIds.includes(d.exampleId));
 await page.reload({waitUntil:'networkidle'});await nav(page,'recovery');await page.locator('[data-recovery-action="open"]').click();assert.equal(await page.locator('#recovery-control input:checked').count(),5);assert.deepEqual((await draft(page)).answers,(await page.locator('#recovery-control input:checked').evaluateAll(xs=>xs.map(x=>Number(x.value)))));
 await page.locator('#recovery-control [type="submit"]').click();let w=await space(page),a=w.assessments.find(x=>x.id===d.id);assert.equal(a.correct,5);assert.equal(a.source,'recovery');assert.equal(a.recovery.successful,true);assert.equal(a.questionEvidence.length,5);assert.match(await page.locator('.content').innerText(),/Kısa kontrol başarılı/);
 const snapshot=await page.evaluate(k=>{const w=JSON.parse(localStorage.getItem(k)).workspaces.kpss;return RotaStudentRecovery.snapshot(w,{subjectId:'k-ma',topicId:'k-ma-9'},RotaCore.iso());},KEY);assert.equal(snapshot.recovery.eligible,false);assert.equal(snapshot.recovery.resolved,true);
 assert.ok(w.plan.some(x=>x.source==='spaced_review'&&x.reviewWave===3&&x.date>=a.date));assert.ok(w.plan.some(x=>x.source==='spaced_review'&&x.reviewWave===7&&x.date>a.date));
 await page.reload({waitUntil:'networkidle'});w=await space(page);assert.equal(w.assessments.filter(x=>x.id===d.id).length,1);assert.ok(w.plan.some(x=>x.decisionTrace));await nav(page,'recovery');assert.equal(await page.locator('[data-recovery-action="open"]').count(),0);
 await page.evaluate(k=>{const key=k+':preferences',p=JSON.parse(localStorage.getItem(key)),d=p.recoveryDrafts['k-ma-9'];d.stage='check';d.answers=d.answers.map(x=>(x+1)%5);localStorage.setItem(key,JSON.stringify(p));},KEY);
 await page.reload({waitUntil:'networkidle'});await page.evaluate(()=>RotaRecoveryUI.open('k-ma-9'));assert.equal(await page.locator('#recovery-control').count(),0,'A persisted completed draft cannot become another attempt');assert.match(await page.locator('.content').innerText(),/Kısa kontrol başarılı/);assert.equal((await space(page)).assessments.filter(x=>x.id===d.id).length,1);
 console.log('PASS A: 45/50/55 → micro lesson → worked example → 5 fresh questions → durable result → no repeated repair + 3/7.');
 await page.evaluate(k=>{const s=JSON.parse(localStorage.getItem(k)),w=s.workspaces.kpss,a={...w.assessments[0],id:'new-risk',miniId:'new-risk',date:RotaCore.iso(),created:Date.now()+1,correct:0,wrong:20,questionEvidence:w.assessments[0].questionEvidence.map(q=>({...q,status:'wrong',picked:(q.answer+1)%5}))};w.assessments.push(a);localStorage.setItem(k,JSON.stringify(RotaCore.validateBackup(s)));},KEY);
 await page.reload({waitUntil:'networkidle'});await page.evaluate(()=>RotaRecoveryUI.open('k-ma-9'));assert.notEqual((await draft(page)).id,d.id,'New risk after a completed success must start a new control');assert.equal((await space(page)).assessments.filter(x=>x.id===d.id).length,1);assert.match(await page.locator('.content').innerText(),/Temel mantık/);console.log('PASS later risk: old successful result remains in history and a new targeted control opens.');
 await seed(page);await page.evaluate(k=>{const s=JSON.parse(localStorage.getItem(k)),w=s.workspaces.kpss;w.assessments=RotaQuestionBank.topicTests().filter(t=>t.topicId==='k-ma-9').map((t,i)=>{const answers=t.questions.map((q,j)=>j<6?q.answer:(q.answer+1)%5);return {id:'all-seen-'+i,miniId:t.id,subjectId:t.subjectId,topicId:t.topicId,title:t.title,date:RotaCore.dayAdd(RotaCore.iso(),-4+i),created:Date.now()-86400000*(4-i),total:12,correct:6,wrong:6,blank:0,minutes:12,answers,questionEvidence:RotaQuestionBank.snapshot(t,answers)};});localStorage.setItem(k,JSON.stringify(RotaCore.validateBackup(s)));},KEY);
 await page.reload({waitUntil:'networkidle'});await nav(page,'recovery');await page.locator('[data-recovery-action="open"]').click();const reusedDraft=await draft(page);assert.equal(reusedDraft.plan.practice,true);assert.equal(reusedDraft.plan.reusedQuestionIds.length,5);assert.ok(!reusedDraft.questionIds.includes(reusedDraft.exampleId));await page.locator('[data-recovery-action="example"]').click();await page.locator('[data-recovery-action="check"]').click();assert.match(await page.locator('#recovery-control .notice').innerText(),/Daha önce gördüğün sorularla pekiştirme; bağımsız yeni ölçüm değil/);assert.doesNotMatch(await page.locator('#recovery-control .notice').innerText(),/5 yeni soru/);await answerAll(page);await page.locator('#recovery-control [type="submit"]').click();assert.match(await page.locator('.content').innerText(),/Geçici DENGE/);w=await space(page);assert.equal(w.assessments.find(a=>a.id===reusedDraft.id).recovery.practice,true);await page.reload({waitUntil:'networkidle'});assert.equal((await space(page)).assessments.find(a=>a.id===reusedDraft.id).recovery.reusedQuestionIds.length,5);console.log('PASS exhausted topic: all 48 seen → separate worked example → labeled practice → lower-weight provisional DENGE retained.');
 await seed(page);await nav(page,'recovery');await page.locator('[data-recovery-action="open"]').click();await page.locator('[data-recovery-action="example"]').click();await page.locator('[data-recovery-action="check"]').click();await answerAll(page,false);await page.locator('#recovery-control [type="submit"]').click();assert.match(await page.locator('.content').innerText(),/Biraz daha onarım/);assert.match(await page.locator('.content').innerText(),/karar: ONARIM/);await page.locator('[data-recovery-action="restart"]').click();assert.equal(await page.locator('[data-recovery-action="example"]').count(),1);
 await nav(page,'laboratory');assert.match(await page.locator('.content').innerText(),/gerçek hata nedenini henüz doğrulamadın/);const row=page.locator('.recovery-error-form').first();await row.locator('xpath=..').locator('summary').click();await row.locator('select').selectOption('process');await row.locator('[type="submit"]').click();w=await space(page);assert.ok(w.mistakes.some(m=>m.errorType==='process'&&m.sourceAssessmentId&&m.questionId&&m.inferred===false));await page.reload({waitUntil:'networkidle'});assert.ok((await space(page)).mistakes.some(m=>m.questionId));
 console.log('PASS failure and Wrong Lab: failed control stays repair; explicit per-question error provenance survives reload.');
 await seed(page);await nav(page,'recovery');await page.locator('[data-recovery-action="open"]').click();
 for(const corrupt of ['topic','duplicate','example','version']){
  const previous=await draft(page);
  await page.evaluate(({key,corrupt})=>{const name=key+':preferences',p=JSON.parse(localStorage.getItem(name)),d=p.recoveryDrafts['k-ma-9'];if(corrupt==='topic')d.plan.topicId='k-ma-1';if(corrupt==='duplicate')d.questionIds[1]=d.questionIds[0];if(corrupt==='example')d.exampleId=RotaQuestionBank.topicTests().find(t=>t.topicId==='k-ta-1').questions[0].id;if(corrupt==='version')d.questionVersions[0]=999;localStorage.setItem(name,JSON.stringify(p));},{key:KEY,corrupt});
  await page.reload({waitUntil:'networkidle'});await nav(page,'recovery');await page.locator('[data-recovery-action="open"]').click();const clean=await draft(page);assert.notEqual(clean.id,previous.id,corrupt+' draft must be replaced before teaching/scoring');assert.equal(clean.plan.topicId,'k-ma-9');assert.equal(new Set(clean.questionIds).size,clean.questionIds.length);
 }
 await page.locator('[data-recovery-action="example"]').click();await page.locator('[data-recovery-action="check"]').click();await page.locator('[name="recovery-q-0"][value="2"]').check();const partial=await draft(page);await page.reload({waitUntil:'networkidle'});await nav(page,'recovery');await page.locator('[data-recovery-action="open"]').click();assert.equal((await draft(page)).id,partial.id);assert.deepEqual((await draft(page)).answers,partial.answers);assert.equal((await space(page)).assessments.length,3,'Resuming a partial control creates no assessment');
 console.log('PASS draft safety: cross-topic, duplicate, changed-version questions rejected; partial answers resume; completed result is immutable.');
 await seed(page,{weak:false});await nav(page,'recovery');assert.equal(await page.locator('[data-recovery-action="open"]').count(),0);assert.match(await page.locator('.content').innerText(),/İLERLEME/);console.log('PASS B: strong student has no automatic recovery.');
 await seed(page,{empty:true});await nav(page,'recovery');assert.match(await page.locator('.content').innerText(),/Önce nerede olduğunu ölçelim/);assert.equal(await page.locator('[data-recovery-action="open"]').count(),0);await nav(page,'laboratory');assert.match(await page.locator('.content').innerText(),/Henüz analiz edilecek yanlış kaydı yok/);
 await page.setViewportSize({width:390,height:844});await assertNoOverflow(page);await seed(page);await nav(page,'recovery');await assertNoOverflow(page);await page.locator('[data-recovery-action="open"]').click();await assertNoOverflow(page);await page.locator('[data-recovery-action="example"]').click();await page.locator('[data-recovery-action="check"]').click();await assertNoOverflow(page);
 fs.mkdirSync(new URL('../work/production-evidence/',import.meta.url),{recursive:true});await page.screenshot({path:new URL('../work/production-evidence/recovery-mobile.png',import.meta.url).pathname,fullPage:false});
 await page.evaluate(()=>RotaNative.handleBack({canGoBack:false},()=>{}));assert.equal(await page.locator('#recovery-control').count(),0);assert.ok((await draft(page)).questionIds.length===5);await page.setViewportSize({width:844,height:390});await assertNoOverflow(page);await nav(page,'report');assert.match(await page.locator('.content').innerText(),/GERÇEK SONUÇLARIN/);await assertNoOverflow(page);
 assert.deepEqual(errors,[]);console.log('PASS no-data and mobile: no fabricated diagnosis, 390px control has no horizontal overflow, no browser errors.');
}finally{await browser?.close();server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));fs.rmSync(tmp,{recursive:true,force:true});}
