import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {bank} from './question-bank-load.mjs';
await import('../public/student-recovery.js');
await import('../public/recovery-content.js');
const S=globalThis.RotaStudentRecovery,content=globalThis.RotaRecoveryContent;
const definition=bank.topicTests().find(t=>t.topicId==='k-ma-9'),q=definition.questions[0];
const calc=content.build({...q,skill:'calculation'}),table=content.build({...q,skill:'table'});
assert.notEqual(calc.thinking,table.thinking,'Guidance must use the measured skill, not just the subject');
assert.match(calc.thinking,/Bilinmeyeni/);assert.match(table.thinking,/Satır ve sütun/);
assert.throws(()=>content.build({...q,answer:9}));
assert.throws(()=>content.build({...q,options:[q.options[0],...q.options.slice(0,4)]}));
assert.throws(()=>content.build({...q,qualityStatus:'needs-review'}));
const workspace={exam:'kpss',settings:{track:'lisans'},plan:[],logs:[],mistakes:[],exams:[],assessments:[1,2,3].map(i=>({id:'a'+i,miniId:'m'+i,subjectId:'k-ma',topicId:'k-ma-9',date:'2026-09-2'+i,total:12,correct:5,wrong:7,blank:0}))};
const window={RotaStudentRecovery:S,RotaQuestionBank:bank,RotaRecoveryContent:content};
vm.runInNewContext(fs.readFileSync(new URL('../public/recovery-ui.js',import.meta.url),'utf8'),{window,document:{addEventListener(){}},console});
window.RotaRecoveryUI.bind({workspace:()=>workspace,topics:()=>[{id:'k-ma-9',subjectId:'k-ma',title:'Problemler'}],today:()=> '2026-09-24',subjectName:()=> 'Matematik',mastery:()=>({known:true,score:32}),preferences:()=>({})});
const home=window.RotaRecoveryUI.page(),progress=window.RotaRecoveryUI.progress();
assert.match(home,/Konu ustalığı 32\/100/);assert.match(progress,/Konu ustalığı 32\/100/);
assert.ok(!home.includes('Mastery %')&&!progress.includes('mastery %'),'The smoothed performance estimate must not be a second UI mastery model');
console.log('Recovery UI contracts passed: approved single-answer structure, skill-specific reasoning and canonical route mastery display.');
