-- Çalışma Rotası · Supabase başlangıç şeması
-- Bu dosya migration değildir. Yeni Çalışma Rotası Supabase projesi oluşturulduktan sonra
-- kontrollü biçimde uygulanacak başlangıç SQL'idir.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '' check (char_length(email) <= 320),
  display_name text not null default 'Öğrenci' check (char_length(display_name) <= 80),
  exam text not null default 'kpss' check (exam in ('kpss')),
  target_score numeric,
  daily_minutes integer check (daily_minutes is null or daily_minutes between 10 and 1440),
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create table if not exists public.workspace_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_exam text not null default 'kpss' check (active_exam in ('kpss')),
  schema_version integer not null default 1,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 1 and 80),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists profiles_last_seen_idx on public.profiles(last_seen_at desc);
create index if not exists activity_events_user_created_idx on public.activity_events(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.workspace_state enable row level security;
alter table public.activity_events enable row level security;

create or replace function private.is_current_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
     and exists (
       select 1 from public.profiles p
       where p.id = (select auth.uid())
         and p.is_admin is true
     );
$$;

revoke all on function private.is_current_admin() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_current_admin() to authenticated;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (id = (select auth.uid()) or private.is_current_admin());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (id = (select auth.uid()) and is_admin is false);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

drop policy if exists "workspace_select_own_or_admin" on public.workspace_state;
create policy "workspace_select_own_or_admin"
on public.workspace_state for select
to authenticated
using (user_id = (select auth.uid()) or private.is_current_admin());

drop policy if exists "workspace_insert_own" on public.workspace_state;
create policy "workspace_insert_own"
on public.workspace_state for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "workspace_update_own" on public.workspace_state;
create policy "workspace_update_own"
on public.workspace_state for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "activity_select_own_or_admin" on public.activity_events;
create policy "activity_select_own_or_admin"
on public.activity_events for select
to authenticated
using (user_id = (select auth.uid()) or private.is_current_admin());

drop policy if exists "activity_insert_own" on public.activity_events;
create policy "activity_insert_own"
on public.activity_events for insert
to authenticated
with check (user_id = (select auth.uid()));

revoke all on public.profiles from anon, authenticated;
revoke all on public.workspace_state from anon, authenticated;
revoke all on public.activity_events from anon, authenticated;

grant select on public.profiles to authenticated;
grant insert (id,email,display_name,exam,target_score,daily_minutes,last_seen_at,updated_at) on public.profiles to authenticated;
grant update (email,display_name,exam,target_score,daily_minutes,last_seen_at,updated_at) on public.profiles to authenticated;
grant select, insert, update on public.workspace_state to authenticated;
grant select, insert on public.activity_events to authenticated;
grant usage, select on sequence public.activity_events_id_seq to authenticated;

-- Yönetici hesabı oluşturulduktan sonra veritabanı tarafından:
-- update public.profiles set is_admin = true where email = 'admin@example.com';
